### ISSUE TITLE
Download has been deleted

### ISSUE THREAD

**Issue by r0manas-dev** [pepeleaks/TFT-UNLOCK-CLEANED-SRC#1]
![thorium_T5kH4OHECL](https://github.com/pepeleaks/TFT-UNLOCK-CLEANED-SRC/assets/154978378/c4e42329-339a-42f3-9626-4c53689e5f72)

Can you update the download link?

Thanks for your time and effort! 🙏

**Comment by pepeleaks** [comment]
UPDATED
